# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - web/**
      - rating/**
      - payment/**
      - shipping/** 
      - mysql/** 
      - mongo/** 
    exclude:
      - README.md

variables:
  dockerHubRepo: sonudock/roboshop
  tag: '$(Build.BuildId)'
  dockerHubUser: sonudock
  dockerHubConnection: DockerHubConnection

pool:
  name: cirunner  # name of your agent pool (must match exactly)


stages:
- stage: DetectChanges
  displayName: Detect Changed Services
  jobs:
    - job: Detect
      displayName: Detect Changed Services
      workspace:
        clean: all
      steps:
        - checkout: self
          fetchDepth: 1 
        - script: |
            echo "Fetching full git history..."
            git fetch --unshallow || true
            git fetch --all --tags
          displayName: Ensure full git history
        - bash: |
            echo "Detecting changed services..."
            CHANGED=$(git diff --name-only HEAD~1 HEAD | cut -d/ -f1 | sort -u | grep -E '^(web|rating|payment|shipping)$' || true)
            echo "Detected: $CHANGED" > changes.txt 
            cat changes.txt
            echo "##vso[task.setvariable variable=changedServices;isOutput=true]$CHANGED"
          name: detect
          displayName: Detect Changed Services

    - ${{ each svc in variables.services }}:
        - job: Build
          displayName: Build 
          condition: contains(variables['changedServices'], '${{ svc }}')
          steps:
          - task: Docker@2
            displayName: Build image ${{ svc }}
            inputs:
              command: build
              repository: $(dockerHubUser)/${{ svc }}
              Dockerfile: $(Build.SourcesDirectory)/${{ svc }}/Dockerfile
              tags: |
                $(Build.SourceVersion)
                latest
