# Docker CI for web service only

trigger:
  paths:
    include:
      - web/**
    exclude:
      - README.md

variables:
  dockerHubRepo: sonudock/roboshop
  tag: '$(Build.BuildId)'
  dockerHubUser: sonudock
  dockerHubConnection: DockerHubConnection
  dockerfilePath: '$(Build.SourcesDirectory)/web/Dockerfile'


pool:
  name: cirunner  # name of your agent pool (must match exactly)

stages:
- stage: BuildPush
  displayName: Build and Push Docker Image for Web
  jobs:
    - job: BuildAndPush
      displayName: Build & Push Web Image
      steps:
        - checkout: self
          fetchDepth: 0

        - task: Docker@2
          displayName: Build image for web
          inputs:
            containerRegistry: $(dockerHubConnection)
            command: build
            repository: $(dockerHubRepo)
            # Dockerfile: $(Build.SourcesDirectory)/web/Dockerfile
            Dockerfile: web/Dockerfile
            tags: |
              $(tag)
              latest
        - task: Docker@2
          displayName: Docker Login
          inputs:
            command: login
            containerRegistry: $(dockerHubConnection)

        - task: Docker@2
          displayName: Push image for web
          inputs:
            command: push
            repository: $(dockerHubRepo)
            tags: |
              $(tag)
              latest
            containerRegistry: $(dockerHubConnection)
