# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - web/**
      - rating/**
      - payment/**
      - shipping/** 
      - mysql/** 
      - mongo/** 
    exclude:
      - README.md

variables:
  dockerHubRepo: sonudock/roboshop
  tag: '$(Build.BuildId)'
  dockerHubUser: sonudock
  dockerHubConnection: DockerHubConnection

pool:
  name: cirunner  # name of your agent pool (must match exactly)


stages:
- stage: DetectChanges
  displayName: Detect Changed Services
  jobs:
    - job: Detect
      displayName: Detect Changed Services
      workspace:
        clean: all
      steps:
        - script: |
            echo "Fetching full git history..."
          displayName: Ensure full git history
          